language: objective-c  # Just to be sure we're on OSX, with Homebrew.

install:
  - unset DYLD_LIBRARY_PATH
  - brew update
  - brew tap homebrew/science
  - brew tap homebrew/versions
  # Install dpo/trilinos as tap.
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
  #- brew doctor

env:
  - PKG=travis/travis-testtap/trilinos

script:
  - brew install $(brew deps $PKG)  # No need for verbose mode here.
  - brew install -v $PKG
  - brew test -v $PKG
  - brew audit $PKG --strict

