language: objective-c  # Just to be sure we're on OSX, with Homebrew.

install:
  - unset DYLD_LIBRARY_PATH
  - brew update
  #- brew doctor

env:
  - PKG=dpo/trilinos

script:
  - brew install $(brew deps $PKG)  # No need for verbose mode here.
  - brew install -v $PKG
  - brew test -v $PKG
  - brew audit $PKG --strict

