language: objective-c  # Just to be sure we're on OSX, with Homebrew.

install:
  - unset DYLD_LIBRARY_PATH
  - brew update
  - brew tap homebrew/science
  - brew tap homebrew/versions
  # Install homebrew/trilinos as tap.
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
  #- brew doctor
  - brew reinstall $(brew deps new-trilinos)  # No need for verbose mode here.
  - brew tap homebrew/python
  - brew install numpy

script:
  - brew install new-trilinos
  - brew gist-logs new-trilinos
  - brew test new-trilinos
  - brew audit new-trilinos --strict

